import type { ApiCategory } from "@shared/schema";

export const BASE_API_URL = "https://toxic-api-site.vercel.app";

export const apiCategories: ApiCategory[] = [
  {
    name: "AI",
    icon: "brain",
    description: "AI-powered chat, text generation, and image creation",
    endpoints: [
      {
        name: "Claude AI",
        desc: "Chat with Claude AI model - fast, intelligent responses for any query",
        method: "GET",
        path: "/ai/claude",
        example: "Explain quantum computing in simple terms",
        status: "active",
      },
      {
        name: "Gemini AI",
        desc: "Google Gemini AI chat with multiple model options (Flash, Flash Lite)",
        method: "GET",
        path: "/ai/gemini",
        example: "What is machine learning?",
        status: "active",
      },
      {
        name: "NoteGPT",
        desc: "GPT-4.1 Mini powered AI chat with customizable tone and length",
        method: "GET",
        path: "/ai/notegpt",
        example: "Write a short poem about coding",
        status: "active",
      },
      {
        name: "AI Image Generator",
        desc: "Generate photorealistic or artistic images from text prompts",
        method: "GET",
        path: "/ai/imagine",
        example: "A futuristic city at sunset",
        status: "active",
      },
      {
        name: "Vider AI Art",
        desc: "Create AI-generated artwork and images with Vider engine",
        method: "GET",
        path: "/ai/vider",
        example: "Anime girl with blue hair",
        status: "active",
      },
    ],
  },
  {
    name: "Downloaders",
    icon: "download",
    description: "Download media from popular platforms",
    endpoints: [
      {
        name: "Facebook Video",
        desc: "Download Facebook videos in HD and SD quality with metadata",
        method: "GET",
        path: "/download/facebook",
        example: "https://www.facebook.com/watch?v=example",
        status: "active",
      },
      {
        name: "Instagram",
        desc: "Download Instagram reels, posts, and stories with full metadata",
        method: "GET",
        path: "/download/instagram",
        example: "https://www.instagram.com/reel/example",
        status: "active",
      },
      {
        name: "Twitter/X Video",
        desc: "Download videos and media from Twitter/X posts with preview images",
        method: "GET",
        path: "/download/twitter",
        example: "https://x.com/user/status/123456789",
        status: "active",
      },
      {
        name: "Douyin Video",
        desc: "Download Douyin (Chinese TikTok) videos without watermark",
        method: "GET",
        path: "/download/douyin",
        example: "https://v.douyin.com/example",
        status: "active",
      },
      {
        name: "YouTube Downloader",
        desc: "Download YouTube videos in multiple quality formats with metadata",
        method: "GET",
        path: "/download/youtube",
        example: "https://youtu.be/example",
        status: "active",
      },
      {
        name: "MediaFire",
        desc: "Get direct download links from MediaFire with file details",
        method: "GET",
        path: "/download/mediafire",
        example: "https://www.mediafire.com/file/example",
        status: "active",
      },
      {
        name: "TeraBox",
        desc: "Download files from TeraBox cloud storage with direct links",
        method: "GET",
        path: "/download/terabox",
        example: "https://www.terabox.com/sharing/link?surl=example",
        status: "active",
      },
      {
        name: "GoFile Upload",
        desc: "Upload files to GoFile cloud storage and get shareable links",
        method: "POST",
        path: "/upload/gofile",
        example: "Upload a file to cloud storage",
        status: "active",
      },
      {
        name: "Uplider",
        desc: "Quick file upload service with instant shareable URL",
        method: "POST",
        path: "/upload/uplider",
        example: "Upload a file and get a link",
        status: "active",
      },
    ],
  },
  {
    name: "Anime & Manga",
    icon: "shuffle",
    description: "Anime streaming, manga reading, and donghua content",
    endpoints: [
      {
        name: "Doronime",
        desc: "Search and stream anime with episode listings from Doronime",
        method: "GET",
        path: "/anime/doronime",
        example: "Naruto Shippuden",
        status: "active",
      },
      {
        name: "OtakDesu",
        desc: "Browse and search anime on OtakDesu with detailed info",
        method: "GET",
        path: "/anime/otakdesu",
        example: "One Piece",
        status: "active",
      },
      {
        name: "Donghua Film",
        desc: "Search Chinese animated films (Donghua) with streaming info",
        method: "GET",
        path: "/anime/donghua",
        example: "Soul Land",
        status: "active",
      },
      {
        name: "KomikCast",
        desc: "Read and search manga on KomikCast with chapter listings",
        method: "GET",
        path: "/manga/komikcast",
        example: "Solo Leveling",
        status: "active",
      },
      {
        name: "KomikIndo",
        desc: "Browse manga and manhwa on KomikIndo with full chapters",
        method: "GET",
        path: "/manga/komikindo",
        example: "Tower of God",
        status: "active",
      },
      {
        name: "OppaDrama",
        desc: "Search and stream Korean dramas with episode listings",
        method: "GET",
        path: "/drama/oppadrama",
        example: "Squid Game",
        status: "active",
      },
      {
        name: "DramaBox",
        desc: "Browse short-form drama series on DramaBox platform",
        method: "GET",
        path: "/drama/dramabox",
        example: "Romance drama",
        status: "active",
      },
      {
        name: "Nanobana",
        desc: "Access anime and manga content from Nanobana database",
        method: "GET",
        path: "/anime/nanobana",
        example: "Demon Slayer",
        status: "active",
      },
    ],
  },
  {
    name: "Gaming",
    icon: "wrench",
    description: "Game character info, stats, and profile lookups",
    endpoints: [
      {
        name: "Enka Network",
        desc: "Lookup Genshin Impact player profiles and character builds via Enka Network",
        method: "GET",
        path: "/game/enka",
        example: "800123456",
        status: "active",
      },
      {
        name: "Free Fire Characters",
        desc: "Get Free Fire character stats, abilities, and detailed info",
        method: "GET",
        path: "/game/ff-character",
        example: "Alok",
        status: "active",
      },
      {
        name: "Character Guide",
        desc: "Comprehensive game character guides with tips and builds",
        method: "GET",
        path: "/game/character-guide",
        example: "Genshin Impact Nahida",
        status: "active",
      },
    ],
  },
  {
    name: "Search",
    icon: "search",
    description: "Search across music, apps, memes, and sound effects",
    endpoints: [
      {
        name: "Song Finder",
        desc: "Search for songs and music tracks with Spotify metadata and album art",
        method: "GET",
        path: "/search/song",
        example: "Bohemian Rhapsody",
        status: "active",
      },
      {
        name: "F-Droid Apps",
        desc: "Search open-source Android apps on F-Droid with download links",
        method: "GET",
        path: "/search/fdroid",
        example: "Termux",
        status: "active",
      },
      {
        name: "Meme Templates",
        desc: "Search and browse popular meme templates from ImgFlip",
        method: "GET",
        path: "/search/meme",
        example: "Drake meme",
        status: "active",
      },
      {
        name: "Sound Effects",
        desc: "Search instant sound buttons and effects from MyInstants",
        method: "GET",
        path: "/search/sounds",
        example: "Bruh sound effect",
        status: "active",
      },
    ],
  },
  {
    name: "Tools",
    icon: "activity",
    description: "Image processing, transcription, and utility tools",
    endpoints: [
      {
        name: "Image Upscaler",
        desc: "AI-powered image upscaling and enhancement - increase resolution 2x",
        method: "GET",
        path: "/tools/upscale",
        example: "https://example.com/low-res-image.jpg",
        status: "active",
      },
      {
        name: "YouTube Transcript",
        desc: "Extract full transcripts from YouTube videos with timestamps",
        method: "GET",
        path: "/tools/transcript",
        example: "https://www.youtube.com/watch?v=example",
        status: "active",
      },
      {
        name: "Currency Converter",
        desc: "Real-time currency conversion with XE exchange rates",
        method: "GET",
        path: "/tools/currency",
        example: "1000,IDR,USD",
        status: "active",
      },
      {
        name: "Korean Name Generator",
        desc: "Generate authentic Korean names with meanings and hangul",
        method: "GET",
        path: "/tools/korean-name",
        example: "Generate a Korean name",
        status: "active",
      },
      {
        name: "Random ASCII Art",
        desc: "Generate random ASCII character strings with custom length and charset",
        method: "GET",
        path: "/tools/ascii",
        example: "32",
        status: "active",
      },
    ],
  },
];

export function getCategoryIcon(name: string): string {
  const cat = apiCategories.find(
    (c) => c.name.toLowerCase() === name.toLowerCase(),
  );
  return cat?.icon || "folder";
}

export function getTotalEndpoints(): number {
  return apiCategories.reduce((sum, cat) => sum + cat.endpoints.length, 0);
}

export function getTotalCategories(): number {
  return apiCategories.length;
}
