import type { ApiCategory } from "@shared/schema";

export const BASE_API_URL = "https://toxic-api-site.vercel.app";

export const apiCategories: ApiCategory[] = [
  {
    name: "AI",
    icon: "brain",
    description: "AI-powered chat and text generation endpoints",
    endpoints: [
      {
        name: "AI Chat (OSS 120B)",
        desc: "Chat with OSS 120B AI model - supports thinking mode for complex queries",
        method: "GET",
        path: "/ai/oss",
        example: "Hello, explain quantum computing",
        status: "active",
      },
      {
        name: "AI Image Generator",
        desc: "Generate images from text prompts using AI models",
        method: "GET",
        path: "/ai/imagine",
        example: "A beautiful sunset over mountains",
        status: "active",
      },
      {
        name: "AI Text Summarizer",
        desc: "Summarize long texts into concise paragraphs using AI",
        method: "GET",
        path: "/ai/summarize",
        example: "Long text to summarize...",
        status: "active",
      },
    ],
  },
  {
    name: "Downloaders",
    icon: "download",
    description: "Download media from popular platforms without watermarks",
    endpoints: [
      {
        name: "CapCut Downloader",
        desc: "Download CapCut videos without watermark in high quality",
        method: "GET",
        path: "/download/capcut",
        example: "https://www.capcut.com/t/example",
        status: "active",
      },
      {
        name: "Facebook Video",
        desc: "Download Facebook videos and reels in HD quality",
        method: "GET",
        path: "/download/facebook",
        example: "https://www.facebook.com/watch?v=example",
        status: "active",
      },
      {
        name: "SnackVideo",
        desc: "Download SnackVideo clips without watermark",
        method: "GET",
        path: "/download/snackvideo",
        example: "https://www.snackvideo.com/video/example",
        status: "active",
      },
      {
        name: "Twitter/X Video",
        desc: "Download videos and media from Twitter/X posts",
        method: "GET",
        path: "/download/x",
        example: "https://twitter.com/user/status/example",
        status: "active",
      },
      {
        name: "MediaFire",
        desc: "Get direct download links from MediaFire file sharing",
        method: "GET",
        path: "/download/mediafire",
        example: "https://www.mediafire.com/file/example",
        status: "active",
      },
      {
        name: "TikTok Video",
        desc: "Download TikTok videos without watermark in HD",
        method: "GET",
        path: "/download/tiktok",
        example: "https://www.tiktok.com/@user/video/123",
        status: "active",
      },
      {
        name: "Instagram Reels",
        desc: "Download Instagram reels and posts media",
        method: "GET",
        path: "/download/instagram",
        example: "https://www.instagram.com/reel/example",
        status: "active",
      },
      {
        name: "YouTube Video",
        desc: "Download YouTube videos in multiple quality formats",
        method: "GET",
        path: "/download/youtube",
        example: "https://www.youtube.com/watch?v=example",
        status: "active",
      },
      {
        name: "Pinterest",
        desc: "Download Pinterest images and video pins in HD",
        method: "GET",
        path: "/download/pinterest",
        example: "https://www.pinterest.com/pin/example",
        status: "active",
      },
      {
        name: "Spotify Track",
        desc: "Get Spotify track metadata and preview URLs",
        method: "GET",
        path: "/download/spotify",
        example: "https://open.spotify.com/track/example",
        status: "active",
      },
    ],
  },
  {
    name: "Random",
    icon: "shuffle",
    description: "Random content generators for anime, images, and more",
    endpoints: [
      {
        name: "Blue Archive",
        desc: "Get random Blue Archive character images in HD",
        method: "GET",
        path: "/random/ba",
        status: "active",
      },
      {
        name: "Random Waifu",
        desc: "Get random anime waifu images in HD quality",
        method: "GET",
        path: "/random/waifu",
        status: "active",
      },
      {
        name: "Pap Ayang",
        desc: "Get random couple and aesthetic romantic images",
        method: "GET",
        path: "/random/papayang",
        status: "active",
      },
      {
        name: "Anime Wallpaper",
        desc: "Get random high-resolution anime wallpapers",
        method: "GET",
        path: "/random/anime",
        status: "active",
      },
      {
        name: "Random Meme",
        desc: "Get random memes from various categories",
        method: "GET",
        path: "/random/meme",
        status: "active",
      },
      {
        name: "Random Quote",
        desc: "Get random inspirational and motivational quotes",
        method: "GET",
        path: "/random/quote",
        status: "active",
      },
      {
        name: "Random Joke",
        desc: "Get random jokes and humor content",
        method: "GET",
        path: "/random/joke",
        status: "active",
      },
      {
        name: "Random Fact",
        desc: "Get random interesting and fun facts",
        method: "GET",
        path: "/random/fact",
        status: "active",
      },
      {
        name: "Sports Fact",
        desc: "Get random interesting sports facts and trivia",
        method: "GET",
        path: "/random/sports",
        status: "active",
      },
      {
        name: "Dad Joke",
        desc: "Get classic dad jokes that are so bad they're good",
        method: "GET",
        path: "/random/dadjoke",
        status: "active",
      },
      {
        name: "Riddle",
        desc: "Get random brain-teasing riddles with answers",
        method: "GET",
        path: "/random/riddle",
        status: "active",
      },
      {
        name: "Pickup Line",
        desc: "Get random funny and creative pickup lines",
        method: "GET",
        path: "/random/pickup",
        status: "active",
      },
      {
        name: "Would You Rather",
        desc: "Get random 'Would You Rather' questions for fun",
        method: "GET",
        path: "/random/wyr",
        status: "active",
      },
      {
        name: "Truth or Dare",
        desc: "Get random truth or dare challenges",
        method: "GET",
        path: "/random/tod",
        status: "active",
      },
    ],
  },
  {
    name: "Tools",
    icon: "wrench",
    description: "Image processing and utility tools",
    endpoints: [
      {
        name: "Image Unblur",
        desc: "AI-powered image enhancement - remove blur and upscale quality",
        method: "GET",
        path: "/tools/unblur",
        example: "https://example.com/blurry-image.jpg",
        status: "active",
      },
      {
        name: "Screenshot Website",
        desc: "Capture full-page screenshots of any website URL",
        method: "GET",
        path: "/tools/screenshot",
        example: "https://google.com",
        status: "active",
      },
      {
        name: "QR Code Generator",
        desc: "Generate QR codes from text or URLs instantly",
        method: "GET",
        path: "/tools/qrcode",
        example: "https://example.com",
        status: "active",
      },
      {
        name: "URL Shortener",
        desc: "Shorten long URLs into compact shareable links",
        method: "GET",
        path: "/tools/shorten",
        example: "https://example.com/very-long-url",
        status: "active",
      },
      {
        name: "Color Palette",
        desc: "Extract dominant color palette from any image URL",
        method: "GET",
        path: "/tools/palette",
        example: "https://example.com/image.jpg",
        status: "active",
      },
      {
        name: "Text to Image",
        desc: "Render styled text as an image with custom fonts and colors",
        method: "GET",
        path: "/tools/text2img",
        example: "Hello World",
        status: "active",
      },
      {
        name: "Removebg",
        desc: "Remove background from images using AI processing",
        method: "GET",
        path: "/tools/removebg",
        example: "https://example.com/photo.jpg",
        status: "active",
      },
    ],
  },
  {
    name: "Search",
    icon: "search",
    description: "Search across various platforms and databases",
    endpoints: [
      {
        name: "Google Search",
        desc: "Search the web using Google and get formatted results",
        method: "GET",
        path: "/search/google",
        example: "latest tech news 2025",
        status: "active",
      },
      {
        name: "Wikipedia",
        desc: "Search Wikipedia articles and get summaries",
        method: "GET",
        path: "/search/wikipedia",
        example: "artificial intelligence",
        status: "active",
      },
      {
        name: "GitHub Repos",
        desc: "Search GitHub repositories by keywords",
        method: "GET",
        path: "/search/github",
        example: "react components",
        status: "active",
      },
      {
        name: "NPM Packages",
        desc: "Search NPM packages with details and stats",
        method: "GET",
        path: "/search/npm",
        example: "express middleware",
        status: "active",
      },
      {
        name: "Lyrics Search",
        desc: "Find song lyrics by title or artist name",
        method: "GET",
        path: "/search/lyrics",
        example: "Bohemian Rhapsody Queen",
        status: "active",
      },
      {
        name: "Anime Search",
        desc: "Search for anime series with details, ratings, and synopsis",
        method: "GET",
        path: "/search/anime",
        example: "Naruto Shippuden",
        status: "active",
      },
      {
        name: "Movie Search",
        desc: "Search for movies with ratings, plot, and cast info",
        method: "GET",
        path: "/search/movie",
        example: "Inception",
        status: "active",
      },
      {
        name: "Sticker Search",
        desc: "Find sticker packs and images from various sources",
        method: "GET",
        path: "/search/sticker",
        example: "cute cat",
        status: "active",
      },
    ],
  },
  {
    name: "Information",
    icon: "info",
    description: "Lookup and information retrieval endpoints",
    endpoints: [
      {
        name: "IP Lookup",
        desc: "Get geolocation and ISP details for any IP address",
        method: "GET",
        path: "/info/ip",
        example: "8.8.8.8",
        status: "active",
      },
      {
        name: "Weather",
        desc: "Get current weather data for any city worldwide",
        method: "GET",
        path: "/info/weather",
        example: "Tokyo",
        status: "active",
      },
      {
        name: "Currency Exchange",
        desc: "Get real-time currency exchange rates",
        method: "GET",
        path: "/info/currency",
        example: "USD,EUR",
        status: "active",
      },
      {
        name: "Domain WHOIS",
        desc: "Get WHOIS registration data for any domain",
        method: "GET",
        path: "/info/whois",
        example: "google.com",
        status: "active",
      },
      {
        name: "Translate Text",
        desc: "Translate text between languages with auto-detection",
        method: "GET",
        path: "/info/translate",
        example: "Hello World",
        status: "active",
      },
      {
        name: "Country Info",
        desc: "Get detailed information about any country worldwide",
        method: "GET",
        path: "/info/country",
        example: "Japan",
        status: "active",
      },
      {
        name: "Crypto Price",
        desc: "Get real-time cryptocurrency prices and market data",
        method: "GET",
        path: "/info/crypto",
        example: "bitcoin",
        status: "active",
      },
    ],
  },
  {
    name: "Converter",
    icon: "repeat",
    description: "File and format conversion utilities",
    endpoints: [
      {
        name: "Text to Speech",
        desc: "Convert text into natural-sounding audio speech",
        method: "GET",
        path: "/convert/tts",
        example: "Hello, welcome to Toxic APIs!",
        status: "active",
      },
      {
        name: "Base64 Encode",
        desc: "Encode any text string to Base64 format",
        method: "GET",
        path: "/convert/base64/encode",
        example: "Hello World",
        status: "active",
      },
      {
        name: "Base64 Decode",
        desc: "Decode Base64 encoded strings back to text",
        method: "GET",
        path: "/convert/base64/decode",
        example: "SGVsbG8gV29ybGQ=",
        status: "active",
      },
      {
        name: "Markdown to HTML",
        desc: "Convert Markdown formatted text to clean HTML",
        method: "GET",
        path: "/convert/md2html",
        example: "# Hello **World**",
        status: "active",
      },
    ],
  },
  {
    name: "Monitoring",
    icon: "activity",
    description: "Server health, metrics, and monitoring endpoints",
    endpoints: [
      {
        name: "API Status",
        desc: "Get server status, uptime, and request statistics",
        method: "GET",
        path: "/api/status",
        status: "active",
      },
      {
        name: "Health Check",
        desc: "Detailed health check with system metrics and memory usage",
        method: "GET",
        path: "/api/health",
        status: "active",
      },
      {
        name: "All Endpoints",
        desc: "Get a complete list of all available API endpoints",
        method: "GET",
        path: "/api/endpoints",
        status: "active",
      },
      {
        name: "Cache Statistics",
        desc: "View cache performance metrics - hits, misses, and hit ratio",
        method: "GET",
        path: "/api/cache/stats",
        status: "active",
      },
      {
        name: "Top Endpoints",
        desc: "See the most popular endpoints ranked by request count",
        method: "GET",
        path: "/api/stats/top",
        status: "active",
      },
    ],
  },
];

export function getCategoryIcon(name: string): string {
  const cat = apiCategories.find(
    (c) => c.name.toLowerCase() === name.toLowerCase(),
  );
  return cat?.icon || "folder";
}

export function getTotalEndpoints(): number {
  return apiCategories.reduce((sum, cat) => sum + cat.endpoints.length, 0);
}

export function getTotalCategories(): number {
  return apiCategories.length;
}
