import type { ApiCategory } from "@shared/schema";

export const BASE_API_URL = "";

export const apiCategories: ApiCategory[] = [
  {
    name: "AI",
    icon: "brain",
    description: "AI-powered chat, text generation, and image creation",
    endpoints: [
      {
        name: "Claude AI",
        desc: "Chat with Claude AI model - fast, intelligent responses for any query",
        method: "GET",
        path: "/ai/claude?text=",
        example: "Explain quantum computing in simple terms",
        status: "active",
      },
      {
        name: "Gemini AI",
        desc: "Google Gemini AI chat with multiple model options",
        method: "GET",
        path: "/ai/gemini?text=",
        example: "What is machine learning?",
        status: "active",
      },
      {
        name: "NoteGPT",
        desc: "GPT-4.1 Mini powered AI chat with customizable tone and length",
        method: "GET",
        path: "/ai/notegpt?text=",
        example: "Write a short poem about coding",
        status: "active",
      },
      {
        name: "AI Image Generator",
        desc: "Generate photorealistic or artistic images from text prompts",
        method: "GET",
        path: "/ai/imagine?prompt=",
        example: "A futuristic city at sunset",
        status: "active",
      },
      {
        name: "WormGPT",
        desc: "Unrestricted AI image generation with multiple art styles",
        method: "GET",
        path: "/ai/wormgpt?prompt=",
        example: "Futuristic city at night",
        status: "active",
      },
      {
        name: "Vider AI Art",
        desc: "Create AI-generated artwork and images with Vider engine",
        method: "GET",
        path: "/ai/vider?prompt=",
        example: "Anime girl with blue hair",
        status: "active",
      },
    ],
  },
  {
    name: "Downloaders",
    icon: "download",
    description: "Download media from popular platforms",
    endpoints: [
      {
        name: "Facebook Video",
        desc: "Download Facebook videos in HD and SD quality with metadata",
        method: "GET",
        path: "/download/facebook?url=",
        example: "https://www.facebook.com/watch?v=example",
        status: "active",
      },
      {
        name: "Instagram",
        desc: "Download Instagram reels, posts, and stories with full metadata",
        method: "GET",
        path: "/download/instagram?url=",
        example: "https://www.instagram.com/reel/example",
        status: "active",
      },
      {
        name: "Twitter/X Video",
        desc: "Download videos and media from Twitter/X posts",
        method: "GET",
        path: "/download/x?url=",
        example: "https://x.com/user/status/123456789",
        status: "active",
      },
      {
        name: "Douyin Video",
        desc: "Download Douyin (Chinese TikTok) videos without watermark",
        method: "GET",
        path: "/download/douyin?url=",
        example: "https://v.douyin.com/example",
        status: "active",
      },
      {
        name: "YouTube Downloader",
        desc: "Download YouTube videos in multiple quality formats with metadata",
        method: "GET",
        path: "/download/youtube?url=",
        example: "https://youtu.be/example",
        status: "active",
      },
      {
        name: "YouTube v2",
        desc: "Alternative YouTube downloader with different source",
        method: "GET",
        path: "/download/youtube2?url=",
        example: "https://youtu.be/example",
        status: "active",
      },
      {
        name: "MediaFire",
        desc: "Get direct download links from MediaFire with file details",
        method: "GET",
        path: "/download/mediafire?url=",
        example: "https://www.mediafire.com/file/example",
        status: "active",
      },
      {
        name: "TeraBox",
        desc: "Download files from TeraBox cloud storage with direct links",
        method: "GET",
        path: "/download/terabox?url=",
        example: "https://www.terabox.com/sharing/link?surl=example",
        status: "active",
      },
      {
        name: "YouTube MP3",
        desc: "Convert YouTube videos to MP3 audio with custom bitrate",
        method: "GET",
        path: "/download/ytmp3?url=",
        example: "https://youtube.com/watch?v=dQw4w9WgXcQ",
        status: "active",
      },
      {
        name: "YouTube MP3 v2",
        desc: "Alternative YouTube to MP3 converter with different source",
        method: "GET",
        path: "/download/ytmp3v2?url=",
        example: "https://youtube.com/watch?v=dQw4w9WgXcQ",
        status: "active",
      },
      {
        name: "Downr Universal",
        desc: "Universal video downloader supporting multiple platforms via Downr",
        method: "GET",
        path: "/download/downr?url=",
        example: "https://www.youtube.com/watch?v=example",
        status: "active",
      },
    ],
  },
  {
    name: "Anime & Manga",
    icon: "shuffle",
    description: "Anime streaming, manga reading, and drama content",
    endpoints: [
      {
        name: "Doronime",
        desc: "Search and stream anime with episode listings from Doronime",
        method: "GET",
        path: "/anime/doronime?q=",
        example: "Naruto Shippuden",
        status: "active",
      },
      {
        name: "OtakDesu",
        desc: "Browse and search anime on OtakDesu with detailed info",
        method: "GET",
        path: "/anime/otakdesu?q=",
        example: "One Piece",
        status: "active",
      },
      {
        name: "Donghua Film",
        desc: "Search Chinese animated films (Donghua) with streaming info",
        method: "GET",
        path: "/anime/donghua?q=",
        example: "Soul Land",
        status: "active",
      },
      {
        name: "Nanobana AI",
        desc: "AI-powered anime image generation via Nanobana platform",
        method: "POST",
        path: "/anime/nanobana",
        example: "Requires image upload (POST)",
        status: "active",
      },
      {
        name: "KomikCast",
        desc: "Read and search manga on KomikCast with chapter listings",
        method: "GET",
        path: "/manga/komikcast?q=",
        example: "Solo Leveling",
        status: "active",
      },
      {
        name: "KomikIndo",
        desc: "Browse manga and manhwa on KomikIndo with full chapters",
        method: "GET",
        path: "/manga/komikindo?q=",
        example: "Tower of God",
        status: "active",
      },
      {
        name: "OppaDrama",
        desc: "Search and stream Korean dramas with episode listings",
        method: "GET",
        path: "/drama/oppadrama?q=",
        example: "Squid Game",
        status: "active",
      },
      {
        name: "DramaBox",
        desc: "Browse short-form drama series on DramaBox platform",
        method: "GET",
        path: "/drama/dramabox?q=",
        example: "Romance drama",
        status: "active",
      },
    ],
  },
  {
    name: "Gaming",
    icon: "wrench",
    description: "Game character info, stats, and profile lookups",
    endpoints: [
      {
        name: "Enka Network",
        desc: "Lookup Genshin Impact player profiles and character builds via Enka Network",
        method: "GET",
        path: "/game/enka?uid=",
        example: "800123456",
        status: "active",
      },
      {
        name: "Free Fire Characters",
        desc: "Get Free Fire character stats, abilities, and detailed info",
        method: "GET",
        path: "/game/ff-character",
        example: "List all characters",
        status: "active",
      },
      {
        name: "Character Guide",
        desc: "Comprehensive game character guides with tips and builds",
        method: "GET",
        path: "/game/character-guide?name=",
        example: "Raiden Shogun",
        status: "active",
      },
    ],
  },
  {
    name: "Search",
    icon: "search",
    description: "Search across music, apps, memes, and sound effects",
    endpoints: [
      {
        name: "Song Finder",
        desc: "Search for songs and music tracks with metadata and album art",
        method: "GET",
        path: "/search/song?q=",
        example: "Bohemian Rhapsody",
        status: "active",
      },
      {
        name: "F-Droid Apps",
        desc: "Search open-source Android apps on F-Droid with download links",
        method: "GET",
        path: "/search/fdroid?q=",
        example: "Termux",
        status: "active",
      },
      {
        name: "Meme Templates",
        desc: "Search and browse popular meme templates from ImgFlip",
        method: "GET",
        path: "/search/meme?q=",
        example: "Drake meme",
        status: "active",
      },
      {
        name: "Sound Effects",
        desc: "Browse instant sound buttons and effects from MyInstants",
        method: "GET",
        path: "/search/sounds",
        example: "List all sounds",
        status: "active",
      },
    ],
  },
  {
    name: "Tools",
    icon: "activity",
    description: "Image processing, transcription, and utility tools",
    endpoints: [
      {
        name: "Image Upscaler",
        desc: "AI-powered image upscaling - check status with processing code",
        method: "GET",
        path: "/tools/upscale?code=",
        example: "CHECK_CODE_HERE",
        status: "active",
      },
      {
        name: "YouTube Transcript",
        desc: "Extract full transcripts from YouTube videos with timestamps",
        method: "GET",
        path: "/tools/transcript?url=",
        example: "https://www.youtube.com/watch?v=example",
        status: "active",
      },
      {
        name: "Currency Converter",
        desc: "Real-time currency conversion with live exchange rates",
        method: "GET",
        path: "/tools/currency?amount=&from=&to=",
        example: "1000,USD,IDR",
        status: "active",
      },
      {
        name: "Korean Name Generator",
        desc: "Generate authentic Korean names with gender info",
        method: "GET",
        path: "/tools/korean-name?name=",
        example: "Rizki",
        status: "active",
      },
      {
        name: "Random ASCII Art",
        desc: "Generate random ASCII character strings with custom length",
        method: "GET",
        path: "/tools/ascii?length=",
        example: "32",
        status: "active",
      },
    ],
  },
  {
    name: "Sports",
    icon: "activity",
    description: "Live scores, standings, and results for popular sports",
    endpoints: [
      {
        name: "Football Scores",
        desc: "Get live and recent football/soccer match scores worldwide",
        method: "GET",
        path: "/sports/football",
        example: "Live scores",
        status: "active",
      },
      {
        name: "Football Standings",
        desc: "Get league standings for EPL, La Liga, Bundesliga, and more",
        method: "GET",
        path: "/sports/football-standings?league=",
        example: "epl",
        status: "active",
      },
      {
        name: "NBA Scores",
        desc: "Get current and recent NBA basketball game scores",
        method: "GET",
        path: "/sports/nba",
        example: "Today's games",
        status: "active",
      },
      {
        name: "Cricket Scores",
        desc: "Get live and recent cricket match scores from major leagues",
        method: "GET",
        path: "/sports/cricket",
        example: "Live matches",
        status: "active",
      },
    ],
  },
];

export function getCategoryIcon(name: string): string {
  const cat = apiCategories.find(
    (c) => c.name.toLowerCase() === name.toLowerCase(),
  );
  return cat?.icon || "folder";
}

export function getTotalEndpoints(): number {
  return apiCategories.reduce((sum, cat) => sum + cat.endpoints.length, 0);
}

export function getTotalCategories(): number {
  return apiCategories.length;
}
